import Providers from "@/app/Providers";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Healthy Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <section className="mx-auto flex max-w-screen-2xl flex-col items-center justify-center">
        {/* <div className="mx-auto flex w-full items-center space-x-2 rounded-md border p-2">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="h-5 w-5 flex-none text-gray-300"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
          />
        </svg>
        <input
          className="w-full appearance-none bg-white text-gray-500 placeholder-gray-500 outline-none sm:w-auto"
          type="text"
          placeholder="Search"
        />
      </div> */}
        {children}
      </section>
    </>
  );
}
