import Providers from "@/app/Providers";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Healthy Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
