export const metadata = {
  title: "Healthy Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <section className="mx-auto flex max-w-7xl flex-col items-center justify-center">
        {children}
      </section>
    </>
  );
}
