import Providers from "@/app/Providers";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Healthy Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <section className="mx-auto flex max-w-screen-2xl flex-col items-center justify-center md:w-[800px]">
        {children}
      </section>
    </>
  );
}
